name: picking_analysis
channels:
  - gurobi
  - defaults
dependencies:
  - gurobi=9.1.0=py38_0
  - numpy=1.19.2=py38h456fd55_0
  - numpy-base=1.19.2=py38hcfb5961_0
  - pandas=1.1.3=py38hb1e8313_0
  - pip=20.2.4=py38hecd8cb5_0
  - python=3.7
  - pip:
    - fbprophet==0.7.1
    - flask==1.1.2
    - matplotlib==3.3.3
    - setuptools-git==1.2
    - xlrd==1.2.0
    - python-dateutil==2.8.1

