name: picking_analysis
channels:
  - gurobi
  - defaults
dependencies:
  - gurobi
  - numpy
  - numpy-base
  - pandas
  - pip
  - python
  - pip:
    - fbprophet
    - flask
    - matplotlib
    - setuptools-git
    - xlrd
    - python-dateutil
